name: commit

on:
  workflow_dispatch:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  PYTHONUTF8: 1

jobs:
  build:
    strategy:
      matrix:
        env-version: 
          - os: "ubuntu-latest"
            python: 3.6
          - os: "ubuntu-latest"
            python: 3.9
          - os: "windows-latest"
            python: 3.9
          - os: "macos-latest"
            python: 3.9

    runs-on: ${{ matrix.env-version.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python ${{ matrix.env-version.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.env-version.python }}

      - name: setup
        run: |
          python -m pip install --upgrade pip
          pip3 install --upgrade click==8.0.2 pyinstaller

      - name: install
        run: make install-dev

      - name: lint
        run: make lint

      - name: coverage
        run: make coverage

      - name: package
        run: python3 -m build

      - name: compile .exe
        if: matrix.env-version.os == 'windows-latest'
        run: |
          pyinstaller --clean --noconfirm --strip --noupx --console --onefile --add-data 'whispers/config.yml;whispers' --add-data 'whispers/rules/*.yml;whispers/rules' --name whispers.exe whispers/main.py
          dist/whispers.exe --help
          dist/whispers.exe --init

      - name: compile .bin
        if: matrix.env-version.os != 'windows-latest'
        run: |
          pyinstaller --clean --noconfirm --strip --noupx --console --onefile --add-data 'whispers/config.yml:whispers' --add-data 'whispers/rules/*.yml:whispers/rules' --name whispers.bin whispers/main.py
          dist/whispers.bin --help
          dist/whispers.bin --init
